const Joi = require("joi");

function validateOrder(req, res, next) {
  const schema = Joi.object({
    // ----- existing fields (unchanged) -----
    stall_id: Joi.number().integer().positive().required(),
    items: Joi.array().min(1).items(
      Joi.object({
        menu_item_id: Joi.number().integer().positive().required(),
        quantity: Joi.number().integer().positive().required()
      })
    ).required(),
    promo_code: Joi.string().trim().max(50).optional(),

    // ----- BED-231: new checkout detail fields -----
    // All optional at the schema level so a simple order still passes,
    // but each is format-checked when it IS sent.

    // The checkout id generated by the frontend (max 30 chars).
    checkout_id: Joi.string().trim().max(30).optional(),

    // Must be exactly one of these two words if provided.
    collection_method: Joi.string().valid("Pickup", "Delivery").optional(),

    // Must be one of the three payment types if provided.
    payment_method: Joi.string().valid("card", "paynow", "cash").optional(),

    // The delivery fee must be a number that is zero or more.
    delivery_charge: Joi.number().min(0).optional().allow(null),

    // Delivery address is REQUIRED only when collection_method is "Delivery".
    // .when() means "apply a different rule depending on another field".
    delivery_address: Joi.string().trim().max(255).when("collection_method", {
      is: "Delivery",
      then: Joi.required(),                 // must be present for delivery
      otherwise: Joi.optional().allow(null, "")   // ignored for pickup
    }),

    // Postal code must be exactly 6 digits, and is REQUIRED only for Delivery.
    postal_code: Joi.string().trim().pattern(/^\d{6}$/).when("collection_method", {
      is: "Delivery",
      then: Joi.required(),
      otherwise: Joi.optional().allow(null, "")
    })
  });

  const validation = schema.validate(req.body, { abortEarly: false });

  if (validation.error) {
    return res.status(400).json({
      message: "Validation failed.",
      errors: validation.error.details.map((detail) => detail.message)
    });
  }

  next();
}

// BED-92: same shape as validateOrder, but promo_code is required here -
// there's no reason to call the preview endpoint without one.
function validatePromoPreview(req, res, next) {
  const schema = Joi.object({
    stall_id: Joi.number().integer().positive().required(),
    items: Joi.array().min(1).items(
      Joi.object({
        menu_item_id: Joi.number().integer().positive().required(),
        quantity: Joi.number().integer().positive().required()
      })
    ).required(),
    promo_code: Joi.string().trim().min(1).max(50).required()
  });

  const validation = schema.validate(req.body, { abortEarly: false });

  if (validation.error) {
    return res.status(400).json({
      message: "Validation failed.",
      errors: validation.error.details.map((detail) => detail.message)
    });
  }

  next();
}

function validateOrderStatus(req, res, next) {
  const schema = Joi.object({
    order_status: Joi.string()
      .valid("Pending", "Preparing", "Ready", "Completed", "Cancelled")
      .required()
  });

  const validation = schema.validate(req.body, { abortEarly: false });

  if (validation.error) {
    return res.status(400).json({
      message: "Validation failed.",
      errors: validation.error.details.map((detail) => detail.message)
    });
  }

  next();
}

module.exports = { validateOrder, validatePromoPreview, validateOrderStatus };